export const metadata = {
  title: 'Search',
  description: 'Generated by create next app',
};

export default function SearchPage() {
  return (
    <>
      <div>
        <h1>FindAmusician - Search</h1>
      </div>
      <div>{/* <SearchForm /> */}</div>
      {/* <main>FindAmusician - Search</main> */}
    </>
  );
}
