import styles from './page.module.scss';

export const metadata = {
  title: 'Site notice',
  description: 'Generated by create next app',
};

export default function SiteNoticePage() {
  return (
    <>
      <div>
        <h1>FindAmusician - Site notice</h1>
      </div>
      {/* <main>FindAmusician - Site notice</main>; */}
      <section className={styles.contactussection}>
        <div>
          <h2>Our address</h2>
        </div>
        <section className={styles.cusubsection}>
          <div>
            <h4>Email: customersupport@findamusician.at</h4>
          </div>
          <section className={styles.contactsubsubsection}>
            <div>
              FindAmusician LLC
              <br />
              Lorem ipsum street 3
              <br />
              1150 Vienna
              <br />
              Austria
            </div>
          </section>
        </section>
      </section>
    </>
  );
}
