import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import { getValidSessionByToken } from '../../../database/sessions';

export const metadata = {
  title: 'Log out',
  description: 'Generated by create next app',
};

type Props = { searchParams: { returnTo?: string | string[] } };

export default async function LogOutPage({ searchParams }: Props) {
  //  if the user is NOT logged in redirect to login

  // 1. Check if the sessionToken cookie exit
  const sessionTokenCookie = cookies().get('sessionToken');
  // 2. check if the sessionToken has a valid session
  const session =
    sessionTokenCookie &&
    (await getValidSessionByToken(sessionTokenCookie.value));

  // 3. Either redirect or render the login form
  if (!session) redirect('/login');

  // console.log('My search params', searchParams);

  return <main>FindAmusician - Log out</main>;
}
