import styles from './page.module.scss';

export const metadata = {
  title: 'FAQs',
  description: 'Generated by create next app',
};

export default function FaqsPage() {
  return (
    <>
      <div>
        <h1>FindAmusician - FAQs</h1>
      </div>
      {/* <main>FindAmusician - FAQs</main>; */}
      <section className={styles.contactussection}>
        <div>
          <h2>What does ...?</h2>
        </div>
        <section className={styles.cusubsection}>
          <div>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
            rhoncus nisi laoreet laoreet congue. Donec a feugiat mi. Cras tortor
            ipsum, laoreet eu maximus ut, facilisis eget arcu. In gravida lacus
            in leo eleifend aliquam.
          </div>
        </section>
      </section>
      <section className={styles.contactussection}>
        <div>
          <h2>How do ...?</h2>
        </div>
        <section className={styles.cusubsection}>
          <div>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
            rhoncus nisi laoreet laoreet congue. Donec a feugiat mi. Cras tortor
            ipsum, laoreet eu maximus ut, facilisis eget arcu. In gravida lacus
            in leo eleifend aliquam.
          </div>
        </section>
      </section>
      <section className={styles.contactussection}>
        <div>
          <h2>When can ...?</h2>
        </div>
        <section className={styles.cusubsection}>
          <div>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
            rhoncus nisi laoreet laoreet congue. Donec a feugiat mi. Cras tortor
            ipsum, laoreet eu maximus ut, facilisis eget arcu. In gravida lacus
            in leo eleifend aliquam.
          </div>
        </section>
      </section>
    </>
  );
}
