import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';
import { getValidSessionByToken } from '../../../database/sessions';
import LoginForm from './LoginForm';
import styles from './page.module.scss';

export const metadata = {
  title: 'Log in',
  description: 'Generated by create next app',
};

type Props = { searchParams: { returnTo?: string | string[] } };

export default async function LogInPage({ searchParams }: Props) {
  // if the user is logged in redirect

  // 1. Check if the sessionToken cookie exit
  const sessionTokenCookie = cookies().get('sessionToken');
  // 2. check if the sessionToken has a valid session
  const session =
    sessionTokenCookie &&
    (await getValidSessionByToken(sessionTokenCookie.value));

  // 3. Either redirect or render the login form
  if (session) redirect('/');

  console.log('My search params', searchParams);
  return (
    <>
      <div>
        <h1>FindAmusician - Log in</h1>
      </div>
      <div className={styles.loginformborder}>
        <LoginForm returnTo={searchParams.returnTo} />
      </div>
      {/* <main>FindAmusician - Log in</main> */}
    </>
  );
}
